### ISSUE TITLE
Kernel 6.12.17: e5500: KVM HV compilation error

### ISSUE THREAD

**Issue by chzigotzky** [chzigotzky/kernels#6]
The stable long-term kernel 6.12.17 cannot compile with KVM HV support anymore.

Error messages:

```
arch/powerpc/kvm/e500_mmu_host.c: In function 'kvmppc_e500_shadow_map':
arch/powerpc/kvm/e500_mmu_host.c:447:9: error: implicit declaration of function '__kvm_faultin_pfn' [-Werror=implicit-function-declaration]
   pfn = __kvm_faultin_pfn(slot, gfn, FOLL_WRITE, NULL, &page);
         ^~~~~~~~~~~~~~~~~
  CC      kernel/notifier.o
arch/powerpc/kvm/e500_mmu_host.c:500:2: error: implicit declaration of function 'kvm_release_faultin_page'; did you mean 'kvm_read_guest_page'? [-Werror=implicit-function-declaration]
  kvm_release_faultin_page(kvm, page, !!ret, writable);
```

**Comment by chzigotzky** [comment]
I reported this issue to the kernel developers today.

Link: [[Kernel 6.12.17] [PowerPC e5500] KVM HV compilation error](https://lists.ozlabs.org/pipermail/linuxppc-dev/2025-March/281942.html)

**Comment by chzigotzky** [comment]
> All now reverted, sorry about that. greg k-h

Link: [[Kernel 6.12.17] [PowerPC e5500] KVM HV compilation error](https://lists.ozlabs.org/pipermail/linuxppc-dev/2025-March/282054.html)

The bad commit has not been reverted in kernel 6.12.18 yet, but perhaps in the next kernel 6.12.19.

**Comment by chzigotzky** [comment]
I successfully compiled the stable long-term kernel 6.12.19 with KVM HV support today. :-)
Today, I tested it successfully.

![Image](https://github.com/user-attachments/assets/c31757cf-f479-43b9-984e-95c2d466d3ef)
